FROM node:12.18.1-slim

COPY practica_creativa2/bookinfo/src/ratings/package.json /opt/microservicios
COPY practica_creativa2/bookinfo/src/ratings/ratings.js /opt/microservicios

ARG service_version
ENV SERVICE_VERSION v1

#instalar dependencias
RUN npm install

EXPOSE 9080

WORKDIR /opt/microservices/
CMD ["node", "ratings.js", "9080"]


