version: '3.0'

services:
  productpage:
    build: 
      context: .
      dockerfile: dockerfile_productpage
    container_name: 34-productpage
    image: 34/productpage
    port:
      - "9080:9080"
    environment:
      - GROUP_NUMBER=34
    
  details:
    build: 
      context: .
      dockerfile: dockerfile_details
    container_name: 34-details
    image: 34/details
    port:
      - "9080"
    environment:
      - SERVICE_VERSION=v3
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
     
  reviews:
    build:
        context: practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg
    container_name: 34-reviews
    image: 34/reviews
    port:
      - "9080"
    environment:
      - ENABLE_RATINGS=true
      - SERVICE_VERSION=v3
      - STAR_COLOR=red
      
  ratings:
    build: 
      context: .
      dockerfile: dockerfile_ratings
    container_name: 34-ratings
    image: 34/ratings
    port:
      - "9080"
    environment:
      - SERVICE_VERSION=v3
  
