FROM ruby:2.7.1-slim

#Copiamos fichero details.rb en /opt/microservices/
COPY practica_creativa2/bookinfo/src/details/details.rb /opt/microservices/

#Variables
ARG service_version
ENV SERVICE_VERSION v1
ARG enable_external_book_service
ENV ENABLE_EXTERNAL_BOOK_SERVICE true

EXPOSE 9080

WORKDIR /opt/microservices/

CMD ["ruby", "details.rb", "9080"]
