FROM python:3.9.2

ENV GROUP_NUMBER 34

RUN apt-get update
RUN apt-get install git
#RUN apt-get install python3-pip
RUN git clone https://github.com/CDPS-ETSIT/practica_creativa2.git

#RUN pip install -r requirements.txt
#Dentro de productpage instalamos requirements
COPY requirements.py .
RUN python3 requirements.py

EXPOSE 9080

CMD ["python3", "./practica_creativa2/bookinfo/src/productpage/productpage.py", "9080"]
